apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-seguridad-deploy
  labels:
    name: microservice-seguridad-deploy
    app: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-seguridad
      type: microservice
  template:
    metadata:
      name: microservice-seguridad-pod
      labels:
        app: microservice-seguridad
        type: microservice
    spec:
      containers:
        - name: microservice-seguridad-app
          image: alrare/serviciosapiseguridad:latest
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__ConexionDB
              value: Server=mssql-service;Database=Seguridad;User=[user];Password=[pass]
