apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  labels:
    app: microservice-seguridad
    type: microservice
spec:
  containers:
    - name: microservice-seguridad-app
      image: alrare/serviciosapiseguridad:latest
      ports:
        - containerPort: 8080
      env:
        - name: ConnectionStrings__ConexionDB
          value: Server=mssql-service;Database=Seguridad;User=[user];Password=[pass]
